### ISSUE TITLE
Support for v7 Runtime

### ISSUE THREAD

**Issue by blueelvis** [DataThirstLtd/databricksConnectDocker#1]
Hi!

Could you please push and add support for the Azure Databricks Runtime Version 7? (7.0 (includes Apache Spark 3.0.0, Scala 2.12))

-Pranav

**Comment by simondmorias** [comment]
Sorry for the delay - databricks only just released databricks-connect for v7 so I was stuck waiting. It is now available (tag 7.1.0)
