### ISSUE TITLE
attempt to pull results in manifiest error

### ISSUE THREAD

**Issue by Freewilly3d** [DataThirstLtd/databricksConnectDocker#13]
Attempted to pull and received a manifest error

**Comment by simondmorias** [comment]
Please provide steps to reproduce this. I can pull the image using the readme example config (no changes except latest tag) and it works fine. No other complaints.

**Comment by Freewilly3d** [comment]
It appears that the issues is you don’t have a latest tag in docker hub and I need to specify a tag that is there.

**Comment by simondmorias** [comment]
Ah yes. The version must align to your databricks runtime version otherwise you get very random errors. For this reason we do not publish a latest tag.

________________________________

**Comment by Freewilly3d** [comment]
Thanks, I get it now.
