### ISSUE TITLE
Magic keywords

### ISSUE THREAD

**Issue by francisco-ltech** [DataThirstLtd/databricksConnectDocker#2]
Is there any extra configuration to support things like: 

# COMMAND ----------

# MAGIC %run ./another_notebook

# COMMAND ----------

.. rest of the main Notebook

**Comment by simondmorias** [comment]
Databricks-connect does not support magic commands by default. Whilst I've seen people use local notebooks in vscode I've never tried it.
If you want to use notebooks I would stick to the main web UI rather than databricks-connect.
